### PR TITLE
Add toot about Ariadne's death-defying stunt

### PR DESCRIPTION
**Pull request by jdolitsky**

### CODE REVIEW

**Review by strongjz — APPROVED** [review]

**Review by denhamparry — APPROVED** [review]
```
              ___
             /  _\
             | /\_|
          __-'' _'
         ----'-.
            |#\#)_,_
            )##\__ _\__.-. 
    -  .-  (###)   '---.  `.
 -   __\____`.#\(      )  L(|
   .'__//\    \#)`-._.' / \\==.
  /_/_//\_\_  /#/  ### / //\\ \
   |(________(##)___/-' '| (_) |
____\___/_________________\___/________________________________________
```

**Comment by kaniini** [comment]
well, that is an interesting way to describe building .NET

**Review by kaniini — CHANGES_REQUESTED** [review]
i think we should stick to actually discussing .NET :p

**Comment by jdolitsky** [comment]
Shoot, OK... I'm sure we will be able to recover the security deposit. Please see https://github.com/wolfi-dev/community/pull/11

**Pull request closed without merging**
